version: '3.1'

services:

  db-gimnasio:
    image: mysql:latest
    command: --mysql-native-password=ON
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: zx76wbz7FG89k
    ports:
      - 33307:3306

  adminer:
    image: adminer:latest
    restart: "no"
    ports:
      - 8182:8080

