version: '3.1'

services:

  db-gimnasio:
    image: mysql:latest
    command: --mysql-native-password=ON
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - ${MYSQL_PORT}:3306

  adminer:
    image: adminer:latest
    restart: "no"
    ports:
      - ${ADMINER_PORT}:8080

